# Labortory work 1

In [85]:
import numpy as np

topic: Binary relationships

Objective: to study the properties of binary relations, operations on relations, to acquire skills of decision-making based on given
relations

## постановка індивідуального завдання;

Перевірити, чи буде дане відношення рефлексивним, антирефлексивним,
симетричним, антисиметричним, асиметричним, транзитивним. Відшукати
для нього найбільший, найменший , максимальний та мінімальний елементи,
якщо такі існують, і побудувати обернене й додаткове відношення.

In [86]:
R = np.array(
    [
        [1, 1, 1, 1, 0],
        [1, 1, 0, 0, 1],
        [1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [0, 1, 0, 0, 0]
    ]
)

## Relationship and tasks

не має найкращих елементів 

- Відношення R називається рефлексивним, якщо x R x для будь-якого елемента x∈Ω.
У матриці рефлексивного відношення на головній діагоналі розміщуються одиниці, тобто елемент матриці aij = ,1 якщо i = j .

- Відношення R називається антирефлексивним, коли
твердження x R y означає, що x ≠ y ∀ ∈x Ω.
- У матриці антирефлексивного відношення елементи головної діагоналі
дорівнюють нулю, тобто aij = ,0 якщо i = j .

In [87]:
ref = []
def reflexion(R):
    for i in range(len(R)):
        ref.append(R[i][i])
    result_reflexion = ref[1:] == ref[:-1] and ref[1] == 1
    result_anti_reflexion = ref[1:] == ref[:-1] and ref[1] == 0
    return f" Відношення є рефлексивним: {result_reflexion}, відношення є антирефлексивним: {result_anti_reflexion}"

In [88]:
reflexion(R)

' Відношення є рефлексивним: False, відношення є антирефлексивним: False'

- Відношення R називається асиметричним, якщо
= ∅ −1  RR (тобто з двох виразів x R y та y R x хоча б один не відповідає
дійсності).

- У матриці симетричного відношення 0 aa jiij = 0 для всіх значень i, j.
Інакше кажучи, з двох симетричних елементів aij і a ji хоча б один обов’язково
дорівнює 0.

- Відношення R називається антисиметричним,
якщо твердження x R y та y R x можуть бути правильними одночасно тоді й
тільки тоді, коли x = y.
- У матриці антисиметричного відношення 0 aa jiij =∧ , коли i ≠ j .

In [89]:
def sym(R):
    sym, antysym, asym = True, True, True

    for i in range(len(R)):
        for j in range(len(R[0])):
            if R[i][j] != R[j][i]:
                sym = False
            if i != j and R[i][j] == 1 == R[j][i]:
                antysym = False
            if R[i][j] ==  R[j][i] == 1:
                asym = False
    return f" Відношення є симетричним : {sym}, відношення є антисиметричним: {antysym}, відношення є асиметричним: {asym}"

In [90]:
sym(R)

' Відношення є симетричним : False, відношення є антисиметричним: False, відношення є асиметричним: False'

- Відношення R називається транзитивним, якщо
2 R R £ ( тобто, коли з тверджень x R z та z R y випливає, що x R y ).
Транзитивними є відношення «більше або дорівнює», «менше», «бути
старшим», «вчитися в одній групі».


In [91]:
def transitive(R):
    r_2 = R@R
    result = True
    for i in range(len(R)):
        for j in range(len(R[0])):
            if r_2[i][j] > R[i][j]:
                result = False
    return f" Відношення є транзитивним : {result}"

In [92]:
transitive(R)

' Відношення є транзитивним : False'

- Для визначення максимальних і мінімальних елементів побудуємо строге
відношення, відповідне даному,

In [93]:
def min_max(R):
    R_S = ((R - np.transpose(R))>0)*1
    print(R_S)

    max, min = [], []

    for i in range(R.shape[0]):
        if (R_S[i]==0).all():
            min.append(i+1)

    for i in range(R.shape[0]):
        if (R_S[..., i]==0).all():
            max.append(i+1)

    return min, max

In [94]:
min_max(R)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]


([1, 2, 5], [1, 2, 3, 4])

In [95]:
def larg_tin(R):
    larg = "-"
    tiny = "-"

    for i in range(R.shape[0]):
        if (R[i]==1).all():
            larg = i+1

    for i in range(R.shape[0]):
        if (R[..., i]==1).all():
            tiny = i+1

    return f'Найбільший елемент: {larg}, найменший елемент: {tiny}'

In [96]:
larg_tin(R)

'Найбільший елемент: -, найменший елемент: -'

### обернена та доповнена матриці

In [97]:
def reverse(R):
    result = [[0] * len(R) for _ in range(len(R))]

    for i in range(len(R)):
        for j in range(len(R[0])):
            result[j][i] = R[i][j]

    return result

In [98]:
def print_matrix(R):
    for i in R:
        print(" ".join(str(x) for x in i))

In [99]:
print_matrix(reverse(R))

1 1 1 1 0
1 1 0 0 1
1 0 1 1 0
1 0 1 1 0
0 1 1 1 0


In [100]:
def complemen(R):
    result = []
    for i in range(len(R)):
        row = []  
        for j in range(len(R)):  
            if R[i][j] == 0:
                row.append(1) 
            else:
                row.append(0)  
        result.append(row) 
    return result

In [101]:
print_matrix(complemen(R))

0 0 0 0 1
0 0 1 1 0
0 1 0 0 0
0 1 0 0 0
1 0 1 1 1
